volumes:
  postgres_data: {}

services:
  shop-db:
    image: postgres:alpine
    environment:
      - 'POSTGRES_DB=shop'
      - 'POSTGRES_PASSWORD=shop'
      - 'POSTGRES_USER=shop'
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  shop-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    image: 'shop-backend'
    ports:
       - "8080:8080"
    depends_on:
      - shop-db

