volumes:
  postgres_data: {}

services:
  shop-db:
    image: postgres:16-alpine
    environment:
      - 'POSTGRES_DB=shop'
      - 'POSTGRES_PASSWORD=shop'
      - 'POSTGRES_USER=shop'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  shop-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop-backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
       - "8080:8080"
    depends_on:
      - shop-db

