spring:
  application:
    name: internet-shop
  datasource:
    url: jdbc:postgresql://shop-db:5432/shop
    username: shop
    password: shop
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.validation: DEBUG
    by.magofrays: DEBUG

server:
  port: 8080
