spring:
  application:
    name: internet-shop

  datasource:
    url: jdbc:hsqldb:mem:myDb
    username: shop
    password: shop
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    contexts: dev

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.validation: DEBUG
    by.magofrays: DEBUG

security:
  jwt:
    expires-hours: 10
    secret: supersecretsossecretsecretsecretASAWQWASASFNANNnsnasnannwqw1214w

server:
  port: 8080
